name: Deploy Website

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'Website/**'
      - '.github/workflows/deploy-website.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Website/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        working-directory: Website
        
      - name: Build website
        run: npm run build
        working-directory: Website
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Website/dist
          
      - name: Debug - List build output
        run: ls -la Website/dist
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
